#!/bin/bash
case "$1" in
  start)   sudo systemctl start finnpayments-backend finnpayments-frontend ;;
  stop)    sudo systemctl stop finnpayments-backend finnpayments-frontend ;;
  restart) sudo systemctl restart finnpayments-backend finnpayments-frontend ;;
  status)  sudo systemctl status finnpayments-backend finnpayments-frontend ;;
  *)       echo "Usage: $0 {start|stop|restart|status}" ;;
esac
